application: ayegemen
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /assets
  static_dir: assets
- url: /js
  static_dir: js
- url: /.*
  script: game1.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest